import psycopg2;
from   classes.amTools  import amTool;

class amDBCreate:
 def __init__( self ):
  """Class for Setting Up Database Schema"""
  self.amTool = amTool();
  self.amTool.log( "Creating Database Schema" );
  self.cfg = self.amTool.load( "./cfg/" , "config" );
  self.createMetaDataTable(   self.cfg["database"]["schema"] , self.cfg["database"]["tables"]["metadata"]   );
  self.createForeignKeyTable( self.cfg["database"]["schema"] , self.cfg["database"]["tables"]["foreignkey"] );

# CREATE TABLE ws_performance_indicator.parcel (
	# id serial NOT NULL,
	# name varchar NOT NULL,
	# polygon polygon NOT NULL,
	# country int NOT NULL,
	# county int NOT NULL
# );
# COMMENT ON TABLE ws_performance_indicator.parcel IS 'List of Parcels';

 def createMetaDataTable( self , schema_name , table_name ):
    try: 
       connection = psycopg2.connect( user     = self.cfg["database"]["connection"]["user"],
                                      password = self.cfg["database"]["connection"]["password"],
                                      host     = self.cfg["database"]["connection"]["host"],
                                      port     = self.cfg["database"]["connection"]["port"],
                                      database = self.cfg["database"]["connection"]["database"] );

       cursor             = connection.cursor();
       create_Table_query = ("CREATE TABLE "+schema_name+"."+table_name+" ( " + 
                              "\"metadata_id\" serial NOT NULL, " + 
                              "\"calculationdate\" timestamp NULL, " + 
                              "\"rulename\" varchar NULL, " + 
                              "\"colorcode\" varchar NULL, " + 
                              "\"parcelcode\" int4 NULL, " + 
                              "\"calendar\" JSON DEFAULT '{}'::jsonb, " + 
                              "\"image\" JSON DEFAULT '[]'::jsonb, " + 
                              "\"cultivationdeclaredcode\" int4 NULL, " + 
                              "\"cultivationdeclaredname\" varchar NULL, " + 
                              "\"cultivation1stpredictioncode\" int4 NULL, " + 
                              "\"probability1stprediction\" float8 NULL, " + 
                              "\"cultivation2ndpredictioncode\" int4 NULL, " + 
                              "\"probability2stprediction\" float8 NULL, " + 
                              "layer_id int4 NOT NULL, " + 
                              "layer_name varchar NOT NULL, " + 
                              "CONSTRAINT layer_meta_pkey PRIMARY KEY (metadata_id) " + 
                             ");");

       print("Creating table with name " + str( table_name ));
       cursor.execute( create_Table_query );
       cursor.close();
       connection.commit();

    except (Exception, psycopg2.Error) as error :
        print ("Error creating table with name " + str( table_name ) , error);

    finally:
        if(connection):
            connection.close();
            print("DB Connection Closed");
            return True;

 def createForeignKeyTable( self , schema_name , table_name ):
    try: 
       connection = psycopg2.connect( user     = self.cfg["database"]["connection"]["user"],
                                      password = self.cfg["database"]["connection"]["password"],
                                      host     = self.cfg["database"]["connection"]["host"],
                                      port     = self.cfg["database"]["connection"]["port"],
                                      database = self.cfg["database"]["connection"]["database"] );

       cursor             = connection.cursor();
       create_Table_query = ("CREATE TABLE "+schema_name+"."+table_name+" ( " + 
                              "table_schema varchar(32) NOT NULL, " + 
                              "table_name varchar(32) NOT NULL, " + 
                              "pk_column varchar(32) NOT NULL, " + 
                              "pk_column_idx int4 NULL, " + 
                              "pk_policy varchar(32) NULL, " + 
                              "pk_sequence varchar(64) NULL, " + 
                              "CONSTRAINT gt_pk_metadata_pk_policy_check CHECK (((pk_policy)::text = ANY ((ARRAY['sequence'::character varying, 'assigned'::character varying, 'autogenerated'::character varying])::text[]))), " + 
                              "CONSTRAINT gt_pk_metadata_table_schema_table_name_pk_column_key UNIQUE (table_schema, table_name, pk_column) " + 
                            ");");

       print("Creating table with name " + str( table_name ));
       cursor.execute( create_Table_query );
       cursor.close();
       connection.commit();

    except (Exception, psycopg2.Error) as error :
        print ("Error creating table with name " + str( table_name ) , error);

    finally:
        if(connection):
            connection.close();
            print("DB Connection Closed");
            return True;


dbCreate = amDBCreate();